Intro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('perfiles.urls')),
    path('test/', include('Test.urls')),
    path('test2/', include('Test2.urls')),
    path('avatar/',include('Avatar.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Test/urls.py
from django.urls import path
from Test import views

urlpatterns = [
    path('', views.test, name='test'),
    path('delete/<int:ramo_id>/',views.delete,name='delete'),
    path('descanso/',views.descanso,name='descanso'),
    path('updatet1/', views.updatet1, name='updatet1'),
    path('deletet1/<int:ramo_id>/',views.deletet1,name='deletet1')
]

perfiles/urls.py
from django.urls import path
from perfiles import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('home/',views.home, name='home'),
    path('register/',views.register, name='register'),
    path('',views.inicio, name='inicio'),
    path('login/', LoginView.as_view(template_name='perfiles/login.html'),name='login'),
    path('logout/', LogoutView.as_view(template_name='perfiles/inicio.html'), name='logout'),
    path('estudio/', views.hora_estudio, name='estudio'),
    path('cumplido/',views.cumplido, name='cumplido'),
    path('certamen/', views.certamen, name = 'certamen'),
    path('hora_certamen/', views.hora_certamen, name= 'hora_certamen')
    ]

Test/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Ramo(models.Model):
    DIFF=[
      (5, 'Pf, facilísimo'),
      (4, 'Fácil'),
      (3, 'Medio'),
      (2, 'Difícil'),
      (1, 'Muy difícil')
    ]
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='Ramos', null=True)
    ramo = models.CharField(max_length=40)
    dificultad = models.IntegerField(choices=DIFF,null=True)

    def __str__(self):
        return f'{self.ramo}'

class Horario(models.Model):
    DISP=[
    ('Ocupado', 'Ocuapado'),
    ('Libre','Libre'),
    ('Estudiar','Estudiar')
    ]
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='horario', null=True)
    day = models.CharField(max_length=20)
    b1 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '8:15-9:25')
    b2 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '9:35-10:45')
    b3 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '10:55-12:05')
    b4 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '12:15-13:25')
    b5 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '14:30-15:40')
    b6 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '15:50-17:00')
    b7 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '17:10-18:20')
    b8 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '18:30-19:40')
    b9 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '19:50-21:00')
    b10 = models.CharField(max_length=20, choices=DISP, default='Libre',verbose_name = '21:10-22:20')

    def __str__(self):
        return f'Usuario: {self.user} Dia: {self.day}'

class Descanso(models.Model):
    hora = models.DurationField()

    def __str__(self):
        return self.day

perfiles/models.py
from django.db import models
from django.contrib.auth.models import User
from Test.models import Ramo
from datetime import date

# Create your models here.
class Nivel(models.Model):
    name= models.CharField(max_length=10)
    numero = models.IntegerField()

    def __str__(self):
        return self.name

class Exp(models.Model):
    name= models.CharField(max_length=10)
    valor = models.IntegerField()

    def __str__(self):
        return self.name

class Certamen(models.Model):
    HORAS = [
        ('b1','8:15-9:25'),
        ('b2','9:35-10:45'),
        ('b3','10:55-12:05'),
        ('b4','12:15-13:25'),
        ('b5','14:30-15:40'),
        ('b6','15:50-17:00'),
        ('b7','17:10-18:20'),
        ('b8','18:30-19:40'),
        ('b9','19:50-21:00'),
        ('b10','21:10-22:20')
    ]
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    ramo = models.ForeignKey(Ramo, on_delete=models.CASCADE, limit_choices_to={'user_id':'1'}) 
    """ usar limitchoices """
    fecha = models.DateField(default=date.today())
    hora = models.CharField(choices=HORAS, max_length=20, default='b1')
    
    def __str__(self):
        return f'Hora: {self.hora} Ramo: {self.ramo}'

perfiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Certamen


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']
        help_texts = {k:"" for k in fields}


class CertamenForm(forms.ModelForm):
    
    class Meta:
        model = Certamen
        fields = ['ramo','fecha','hora']

    # def __init__(self, *args, **kwargs):
    #     super(CertamenForm,self).__init__(*args,**kwargs)
    #     if self.instance.ramo and self.instance.ramo.id:
    #         user = self.instance.ramo.user.all()
    #         self.fields['user'].queryset = user
            

perfiles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import  authenticate,login
from .forms import UserRegisterForm, CertamenForm
from Test.models import *
from .calendario import crear_calendario, crear_estudio, crear_certamen
from .models import *
from Avatar.models import Accesorios,Caras,Vestuario,contador
from .Google import Create_Service
conacc = [35,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,36]
concar = [18, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16,17,19]
conver = [18, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16,17,19]

# Create your views here.

def home(request):
   nivel=Nivel.objects.get(name='nivelon')
   exp = Exp.objects.get(name='experience')
   supera = Exp.objects.get(name='supera')
   while exp.valor >= supera.valor:
      nivel.numero = nivel.numero + 1
      nivel.save()
      exp.valor = exp.valor - supera.valor
      exp.save()
      supera.valor = supera.valor + 15
      supera.save()
   ac = conacc[contador.objects.get(name='acceso').valor]
   ca = concar[contador.objects.get(name='careta').valor]
   ve = conver[contador.objects.get(name='vesto').valor]
   accesorios = Accesorios.objects.get(id=ac)
   caras = Caras.objects.get(id=ca)
   vestuario = Vestuario.objects.get(id=ve)
   user = request.user
   ramos = Ramo.objects.all().filter(user=user).order_by('id')
   horario = Horario.objects.all().filter(user=user)
   context = {'user':user,'ramos':ramos,'horario':horario,'accesorios':accesorios, 'caras':caras, 'vestuario':vestuario,'nivel':nivel,'exp':exp,'supera':supera}
   return render(request, 'perfiles/home.html',context)

def logout(request):
   return render(request,'logout.html',context={'user':request.user})

def register(request):
   if request.method == 'POST':
      form = UserRegisterForm(request.POST)
      if form.is_valid():
         form.save()
         username = request.POST['username']
         password = request.POST['password1']
         user = authenticate(request,username=username, password =password)
         login(request,user)
         calendario = crear_calendario()


         ##############################################################

         accesorio = contador.objects.get(name='acceso')
         accesorio.valor = 0
         accesorio.save()

         cara = contador.objects.get(name='careta')
         cara.valor = 0
         cara.save()

         ropa = contador.objects.get(name='vesto')
         ropa.valor = 0
         ropa.save()

         nivel = Nivel.objects.get(name='nivelon')
         nivel.numero = 1
         nivel.save()

         exp = Exp.objects.get(name='experience')
         exp.valor = 0
         exp.save()

         supera = Exp.objects.get(name='supera')
         supera.valor = 15
         supera.save()

         ##############################################################

         return redirect('test')
   else:
      form = UserRegisterForm()
   context = {'form':form}
   return render(request, 'perfiles/register.html', context)

def inicio(request):
   # hacer que cuando se vaya inicio se deslogue automaticamente
   return render(request, 'perfiles/inicio.html')


def hora_estudio(request):
   user = request.user
   horarios = Horario.objects.filter(user = user)
   materias = Ramo.objects.filter(user=user).order_by('dificultad')
   eventos = crear_estudio(horarios,materias)
   return redirect('home')

def cumplido(request):
   exp = Exp.objects.get(name='experience')
   exp.valor = exp.valor + 10
   exp.save()
   return redirect('home')

def certamen(request):
   user = request.user
   choices = Ramo.objects.filter(user=user)
   if request.method == 'POST':
      form = CertamenForm(request.POST, instance=Certamen(user=user))
      if form.is_valid():
         form.save()
         return redirect('hora_certamen')
   else:
      form = CertamenForm(instance=Certamen(user=user))
   context = {'form':form}
   return render(request,'perfiles/certamen.html',context)

def hora_certamen(request):
   user = request.user
   certamenes = Certamen.objects.filter(user = user)
   eventos = crear_certamen(certamenes)
   return redirect('home')

perfiles/templates/perfiles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body id="page-top">
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

perfiles/templates/perfiles/certamen.html
{% extends 'perfiles/base.html' %}
{% load static %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">Agregar certamen </a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
    </div>
</nav>

<section class="page-section bg-primary text-white mb-0" id="page-top">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Llene los campos de informacion del certamen</h2>
        <br><br><br>
        <form method="post"> 
            {% csrf_token %}
            <div class="text-center">
                {{form.as_p}}
            </div>
                <button class="btn-xl btn-dark" type="submit" >Enviar</button>
        </form>
        <br><br><br>
    </div>
</section>
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4"></h4>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Bienvenido,    @{{user}}</h4>
                <h4><img src=" {% static 'imagenes/logo task.png' %} " class="img-fluid"/></h4>
            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4"></h4>
                <p class="lead mb-0">
                    
                </p>
            </div>
        </div>
    </div>
</footer>








{% endblock %}




<h1>Prueba</h1>

<form method="post">
    {% csrf_token %}
    {{form}}
    <button >Enviar</button>
</form>

perfiles/templates/perfiles/home.html
{% extends 'perfiles/base.html' %}
{% load static %}
{% block content %}

<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">Inicio</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Ramos</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#horario">Horario</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#opciones">Opciones</a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <img src="{% static 'imagenes/avatar.png' %}" alt="avatar"class="masthead-avatar mb-5"/>
        <img src="{{vestuario.imagen.url}}" class="masthead-avatar mb-5"/> 
        <img src="{{caras.imagen.url}}" class="masthead-avatar mb-5"/>
        <img src=" {{ accesorios.imagen.url }} " class="masthead-avatar mb-5"/>
        
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <a class="btn btn-xl btn-outline-light" href="{% url 'avatar' %}">Personalizar avatar</a>
        <br>
        <p class="masthead-subheading font-weight-light mb-0">Nivel: {{nivel.numero}}      EXP: {{exp.valor}} / {{supera.valor}}</p>
        <br>
        <p class="masthead-subheading font-weight-light mb-0"><a class="btn btn-outline-light btn-social mx-1" href="{% url 'cumplido' %}">+</a>Recordatorio cumplido (+10 EXP)</p>
    </div>
</header>
<!-- Portfolio Section-->
<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Portfolio Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Ramos inscritos</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Portfolio Grid Items-->
        <div class="row justify-content-center">
            {% for ramo in ramos%}
            <li>
                {{ramo.ramo}}  <br>
                Dificultad: {{ramo.get_dificultad_display}}
            </li>
            {% endfor %}
        </div>
    </div>
</section>
<section class="page-section portfolio" id="horario">
    <div class="container">
        <!-- Portfolio Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Horario</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Portfolio Grid Items-->
        <div class="row justify-content-center">
            {% for dia in horario%}
                <div class="col-md-6 col-lg-4 mb-5 text-center">
                    {{dia.day}}: <br><br>
                    <strong>8:15-9:25</strong>: {{dia.b1}} <br>
                    <strong>9:35-10:45</strong> : {{dia.b2}} <br>
                    <strong> 10:55-12:05 </strong>: {{dia.b3}} <br>
                    <strong>12:15-13:25</strong> : {{dia.b4}} <br>
                    <strong> 14:30-15:40</strong>: {{dia.b5}} <br>
                    <strong>15:50-17:00</strong> : {{dia.b6}} <br>
                    <strong>17:10-18:20</strong> : {{dia.b7}} <br>
                    <strong> 18:30-19:40</strong>: {{dia.b8}} <br>
                    <strong> 19:50-21:00</strong>: {{dia.b9}} <br>
                    <strong> 21:10-22:20</strong>: {{dia.b10}} <br>
                </div>
            {% endfor%}
        </div>
        <div class="text-center mt-4">
        <div ><p class="lead"> <a class="btn btn-xl btn-outline-dark" href="{% url 'estudio' %}">Importar datos a Google calendar</a></p></div>
        <div ><p class="lead"> <a class="btn btn-xl btn-outline-dark" href="{% url 'certamen' %}">Agregar certamen</a></p></div>
        <div ><p class="lead"> <a class="btn btn-xl btn-outline-dark" href="https://calendar.google.com" target="_blank" >Ir a Google calendar</a></p></div>
        </div>
    </div>
</section>




<section class="page-section bg-primary text-white mb-0" id="opciones">
    <div class="container">
        <!-- About Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-white">Opciones</h2>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row">
            <div ><p class="lead"> <a class="btn btn-xl btn-outline-light" href="{% url 'updatet1' %}"> Cambiar Test 1</a></p></div>
            <div ><p class="lead"> <a class="btn btn-xl btn-outline-light" href="{% url 'Test2' %}"> Hacer Test 2</a></p></div>
        </div>
        <!-- About Section Button-->
        <div class="text-center mt-4">
            <a class="btn btn-xl btn-dark btn-outline-light" href="{% url 'login' %}">Cambiar usuario</a>
            <a class="btn btn-xl btn-danger btn-outline-light" href="{% url 'logout' %}">Salir</a>
        </div>
    </div>
</section>




<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4"></h4>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Bienvenido,    @{{user}}</h4>
                <h4><img src=" {% static 'imagenes/logo task.png' %} " class="img-fluid"/></h4>
            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4"></h4>
                <p class="lead mb-0">
                    
                </p>
            </div>
        </div>
    </div>
</footer>

<!--
<h1> Inicio </h1>
<p>Ramos inscritos:</p>
<ul>
    {% for ramo in ramos%}
    <li>{{ramo.ramo}} Dificultad: {{ramo.dificultad}}</li>
    {% endfor %}
</ul>
<p>Horario:</p>
<ul>
    {% for dia in horario%}
    <li>{{dia.day}}: <strong>8:15-9:25</strong>: {{dia.b1}} <strong>9:35-10:45</strong> : {{dia.b2}} <strong> 10:55-12:05 </strong>: {{dia.b3}} <strong>12:15-13:25</strong> : {{dia.b4}} <strong> 14:30-15:40</strong>: {{dia.b5}} <strong>15:50-17:00</strong> : {{dia.b6}} <strong>17:10-18:20</strong> : {{dia.b7}} <strong> 18:30-19:40</strong>: {{dia.b8}} <strong> 19:50-21:00</strong>: {{dia.b9}} <strong> 21:10-22:20</strong>: {{dia.b10}}</li>
    {% endfor%}
</ul>
<p><a href="{% url 'estudio' %}">Importar datos a Google calendar</a></p>
<p><a href="{% url 'updatet1' %}">Cambiar Test 1</a></p>
<p><a href="{% url 'Test2' %}">Hacer Test 2</a></p>
<p><a href="{% url 'avatar' %}">Personalizar avatar</a></p>
<p><a href="{% url 'login' %}">Cambiar usuario</a></p>
<p><a href="{% url 'logout' %}">Salir</a></p>

<img src="{% static 'imagenes/avatar.png' %}" alt="avatar"class="heaven"/> 
<td>
    <img src=" {{ accesorios.imagen.url }} " class="eye"/>
</td>
<td>
    <img src="{{caras.imagen.url}}" class="eye"/>
</td>
<td>
    <img src="{{vestuario.imagen.url}}" class="eye"/>
</td>
-->
{% endblock %}

perfiles/templates/perfiles/inicio.html
{% extends 'perfiles/base.html' %}
{% load static %}
{% block content %}

 <h1  style="text-align:center"> Bienvenido a <img src=" {% static 'imagenes/logon.png' %} " class="logo"/></h1>
 <br><br>
 <h2 style="text-align:center">Para iniciar sesión aprete <a href="{% url 'login' %}">aquí</a></h2>
 <h2 style="text-align:center">Para registrarse aprete <a href="{% url 'register' %}">aquí</a></h2>



{% endblock %}

perfiles/templates/perfiles/login.html
{% extends 'perfiles/base.html' %}
{% load static %}
{% block content %}


<section class="page-section bg-primary text-white mb-0" id="opciones">
    <div class="container">
        <h1 style="text-align:center">Ingrese sus datos</h1>
        <br><br>
        <form class="form-floating mb-3" method="post" style="text-align:center">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-dark" type="submit" >Ingresar</button>
        
        </form>
        
        <br><br>
    </div>
</section>
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4"></h4>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Bienvenido</h4>
                <h4><img src=" {% static 'imagenes/logo task.png' %} " class="img-fluid"/></h4>
            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4"></h4>
                <p class="lead mb-0">
                    
                </p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

perfiles/templates/perfiles/logout.html
{% extends 'perfiles/base.html' %}
{% block content %}


<h1>Bye</h1>


{% endblock %}

perfiles/templates/perfiles/register.html
{% extends 'perfiles/base.html' %}
{% load static %}
{% block content %}
<section class="page-section bg-primary text-white mb-0" id="opciones">
    <div class="container">
        <h1 style="text-align:center"> Porfavor registrese</h1>
        <br><br>
        <form class="form-floating mb-3" method="post" style="text-align:center">
            {% csrf_token %}
            {{form.as_p}}
            <br>
            <button class="btn-xl btn btn-info btn-outline-light" type="submit" >Registrar</button>
        </form>
        
        <br><br>
    </div>
</section>
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4"></h4>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Bienvenido</h4>
                <h4><img src=" {% static 'imagenes/logo task.png' %} " class="img-fluid"/></h4>
            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4"></h4>
                <p class="lead mb-0">
                    
                </p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}